server.port: ${PORT:8081}

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  prefix: /api
  routes:
    ai:
      path: /ai/**
      serviceId: bug-wars-ai-crud
    games:
      path: /games/**
      serviceId: bug-wars-game-engine

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    non-secure-port: 80
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'